spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot_learn?characterEncoding=utf8
    username: root
    password: 1qaz2wsx
  jpa:
    database: mysql
    show-sql: true
    #ddl-auto: update 自动更新表结构，如表不存在自动创建，如果修改了表结构，程序启动时执行表结构的同步更新
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImproveNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect